workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable # Specify your Flutter channel (stable, beta, master)
      xcode: latest # Use the latest Xcode version
      cocoapods: default # Ensures CocoaPods is available
      # Add your environment variables here (Optional)

    triggering:
      events:
        - push
        - pull_request

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..

      - name: Build iOS IPA
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/**/*.ipa

    publishing:
      app_store_connect:
        api_key:
          key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID
          private_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true # Set to false if you don’t want automatic submission

      email:
        recipients:
          - your-email@example.com
