workflows:
  ios-simulator-workflow:
    name: iOS Simulator Workflow
    max_build_duration: 60
    environment:
      flutter: stable # Specify your Flutter channel (stable, beta, master)
      xcode: latest # Use the latest Xcode version
      cocoapods: default

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..

      - name: Build iOS app for simulator
        script: |
          flutter build ios --simulator --release

    artifacts:
      - build/ios/**/*.app

    publishing:
      email:
        recipients:
          - your-email@example.com
