workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable # Specify your Flutter channel (stable, beta, master)
      xcode: latest # Use the latest Xcode version
      cocoapods: default # Ensures CocoaPods is available
      # Add any environment variables you need

    triggering:
      events:
        - push
        - pull_request

    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..

      - name: Build iOS IPA
        script: |
          flutter build ipa --release

    artifacts:
      - build/ios/ipa/**/*.ipa

    publishing:
      email:
        recipients:
          - omar.ameer244@gmail.com
